### ISSUE TITLE
Change writing to use iteration.

### ISSUE THREAD

**Issue by jamen** [audiojs/audio#13]
Iteration will be VERY helpful for writing multi-channel data.

For example, the use of generators would make it easy to write two dynamic channels at once:
```javascript
const { PI, sin } = Math;

// Write sine waves
audio.write(function* (t, self) {
  // Channel 1 (first iteration)
  yield self.max * sin(2 * PI / 440 * t);

  // Channel 2 (second iteration)
  yield (self.max - 20) * sin(2 * PI / 1000 * 2);
});
```

With this, you could also use arrays to write static multi-channel data:
```javascript
audio.write([12, 13]);
```

Then you could have single integers like `3` expand to `[3, 3]`
```javascript
audio.write(3);
// Equivalent to
audio.write([3, 3]);
```

**Comment by jamen** [comment]
Note: `write` is asynchronous and should have a callback somewhere.

**Comment by ConnorHartley** [comment]
Could you expand multiple integers for more than two channels in your last example?

**Comment by jamen** [comment]
Yeah, it doesn't literally "expand" I guess.  It would use some system behind the scenes with `audio.channels`, and write the number howmany ever times over.

**Comment by jamen** [comment]
I'm going to close this until I have a better idea of how I want to structure things.
