### ISSUE TITLE
Audio Playback Through Speakers

### ISSUE THREAD

**Issue by robertmain** [audiojs/audio#37]
I'm currently working on a project to play a stream of audio back through the speakers. Can this be done using this project?

**Comment by jamen** [comment]
:wave: not possible yet, see progress at [audio-speaker](https://github.com/audiojs/audio-speaker)

**Comment by robertmain** [comment]
Cool, I'm currently using [node-speaker](https://github.com/TooTallNate/node-speaker) from @TooTallNate
