### ISSUE TITLE
Audio.trim - API Priority

### ISSUE THREAD

**Issue by phil-andrews** [audiojs/audio#40]
Great library! 

Not sure if this is the right place for this but Audio.splice function would be fantastic to have access to. There is no other library for Node that has a splice functions. This whole library is novel against anything else available. Splicing would be big.

Is there a possible way to hack this using `.trim` method?

**Comment by dfcreative** [comment]
I think `audio.remove(fromTime, duration).insert(fragment, time)` would do the same as `splice` in a bit more graceful manner. Btw that is workable now :)

**Comment by phil-andrews** [comment]
Ah, ok. Hadn't thought of that. Thanks for the help.

**Comment by dfcreative** [comment]
Closing, since `trim` method is supported.
