### ISSUE TITLE
.load is not a function

### ISSUE THREAD

**Issue by phil-andrews** [audiojs/audio#41]
```
const audio = require('audio')

const newAudio = new audio()
newAudio.load('https://s3.amazonaws.com/philandrews/hardwell.mp3').then(audio => { 
    console.log(audio)
}, error => {
    console.log(error)
})
```

Error: newAudio.load is not a function

What am I missing here?

**Comment by natesilva** [comment]
The published module seems to be extremely outdated, and is just a single ~100 line file.

Could the maintainers please publish what’s in Git? This looks like a great project, and I’d love to try it out.

**Comment by dfcreative** [comment]
@natesilva I am working hard on making MVP before release, I'll announce & publish once ready, for now please stay tuned and use github repo as a dependency - highly experimental and unstable!

**Comment by daniamurad** [comment]
I am also having the same issue and not sure how to work around with it. I want to use the .slice function

**Comment by dfcreative** [comment]
@daniamurad @phil-andrews use
```js
let Audio = require('audio')
Audio.load('https://s3.amazonaws.com/philandrews/hardwell.mp3').then(audio => {
audio.slice().save()
})
```

**Comment by daniamurad** [comment]
@dfcreative 
I just tried and it says: Audio.load is not a function
I used npm install audio .. but I dont know if it downloaded the completed library or not ..

**Comment by dfcreative** [comment]
@daniamurad please install `npm i audiojs/audio` for now. It is not released in github yet. Please also note that it is highly experimental now, release is coming soon.

**Comment by daniamurad** [comment]
I got this now ..
`speaker` package was not found. Using `audio-sink` instead.

And error: UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: this.buffer.fill is not a function

**Comment by dfcreative** [comment]
@daniamurad simple wav loading/slicing test should work now:

```js
Audio.load('./file.wav').then(audio => {
  audio.slice(.5, 1)
  audio.save('chunk.wav')
})
```

Unfortunately it cannot handle mp3 for now, figuring out the reason.

**Comment by daniamurad** [comment]
Thanks alot it is working for slicing the audio file. 
However if I try to slice same audio file two times for two different duration and save as different names, I get the following error on the second one:
(node:22448) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'getChannelData' of undefined

**Comment by dfcreative** [comment]
@daniamurad ok, this should work with https://github.com/audiojs/audio/commit/d685ad8c80c62c3d8707be4756e96201caebfc4a

```js
Audio.load(localWav).then(a => a.slice(0, 1).save('x.wav'))
Audio.load(localWav, (err, audio) => {
  audio.slice(1, 2).save('y.wav')
})
```

Also I modified `slice` method to make it immutable (return a copy of original file), so you can also do

```js
Audio.load(localWav, (err, a) => {
  a.slice(1, 2).save('x.wav')
  a.slice(2, 3).save('y.wav')
})
```

**Comment by daniamurad** [comment]
Thanks alot @dfcreative its working great !

**Comment by dfcreative** [comment]
@daniamurad my pleasure, glad it helped!
