### ISSUE TITLE
Blob support

### ISSUE THREAD

**Issue by samanmohamadi** [audiojs/audio#47]
Hi, I tried blob but it seems that blob is not supported.
this:
`(new Audio(blob,{length:blob.size}).remove(1,2);`
throws:
`Value must be an array or buffer.`

**Comment by dfcreative** [comment]
@samanmohamadi please use `Audio.decode` for now. Soon (#48) will enable your approach.

```js
Audio.decode(new Blob([lena.mp3]), (err, audio) => {});
```
