### ISSUE TITLE
Issue in playback.js

### ISSUE THREAD

**Issue by dkadrios** [audiojs/audio#49]
I'm encountering "this._parseArgs is not a function" when calling audio.play

Is this a known issue?  I do realize things are in flux at the moment.  I can look into fixing it if you're looking for contributors.  This project seems *very* promising.

**Comment by dfcreative** [comment]
@dkadrios sure, please feel free. It takes releasing [audio-speaker](https://github.com/audiojs/audio-speaker) though first. You can feel free to implement any methods from [the api](https://github.com/audiojs/audio/blob/master/api.md)

**Comment by derhuerst** [comment]
Sorry for closing this. I seem to have clicked close in the wrong tab.

**Comment by dfcreative** [comment]
From https://github.com/audiojs/audio/commit/c3b7e3cd8a0d7ff59ef546c65acb35f97d143258 `play` should work. Needs testing though.
