### ISSUE TITLE
Audio.stream() is not a function

### ISSUE THREAD

**Issue by Drylozu** [audiojs/audio#65]
I'm editing some audio files using Node 12.4 and this package... But at the moment to get the stream using `Audio.stream()` it shows me that isn't a function. Any solution?

**Comment by dy** [comment]
Yeah, sorry, for now that's not ready.
That's highly work in progress, but the work's stopped due to lack of outcome.
I'd recommend any of the analogs.

**Comment by Drylotrans** [comment]
Oh okay, so I inserted and removed some audio and I saved it as `some.wav`. I open it but the file is empty... Another any solution? If there's not, is there any way to convert AudioBufferList to Buffer?
